" ================================================
"           Name:   _vimrc for Win10
"           Author:     NieXi
"           Email:      xilemon3@gmail.com
" ================================================

" General ========================================
" 文件类型侦测
filetype on

" 根据文件加载对应插件
filetype plugin on

" 设置不兼容vi模式
set nocompatible                    

" vim默认寄存器与系统剪切版共享
set clipboard+=unnamed              

" 输入时隐藏鼠标
set mousehide                       

set backspace=2
set nobackup
set noswapfile
set history=1024
set autoread

" Lang & Encoding ================================
set encoding=utf8
set fileencoding=utf-8
let $LANG="zh_CN.UTF-8"

" 设置菜单栏编码
set langmenu=zh_cn.utf-8
" 解决提示信息乱码
language messages zh_CN.utf-8						
" 设置帮助的语言为中文
set helplang=cn										
" 解决菜单栏乱码
source $VIMRUNTIME/delmenu.vim                      
source $VIMRUNTIME/menu.vim

" Plugin =========================================
filetype off
set rtp+=$VIM/vimfiles/bundle/Vundle.vim
call vundle#begin('$VIM/vimfiles/bundle/')

Plugin 'VundleVim/Vundle.vim'

" Theme
Plugin 'altercation/vim-colors-solarized'
Plugin 'tomasr/molokai'
Plugin 'vim-scripts/phd'

" vim-powerline
Plugin 'Lokaltog/vim-powerline'
set laststatus=2

Plugin 'tangledhelix/vim-octopress'

Plugin 'scrooloose/nerdtree'
map <F2> :NERDTreeToggle<CR>

Plugin 'kien/ctrlp.vim'

Plugin 'fholgado/minibufexpl.vim'
let g:miniBufExplMapCTabSwitchBufs = 1

" vim中文文档
Plugin 'magexi/vimcdoc'

" git
Plugin 'vim-gitgutter'

filetype on
call vundle#end()



" 主题配色方案
set background=dark
colorscheme solarized
"colorscheme molokai
"colorscheme phd

" 高亮显示当前行/列
set cursorline						 
set cursorcolumn

"autocmd GUIEnter * simalt ~x		 " 设定windows下 gvim 启动时最大化
winpos 500 100                       " 设定启动位置
set lines=30 columns=90

" 禁止显示工具栏/菜单栏
set guioptions-=T                    
set guioptions-=m

" 禁止显示滚动条
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R

" 使用内置tab样式,而不是gui
set guioptions-=e 					 

set guioptions-=b

" 设置字体
"set guifont=DejaVu_Sans_Mono_for_Powerline:h11:b:cANSI:qDRAFT
set guifont=YaHei_Consolas_Hybrid:h12.5    " :b

" 设置相对行号
"set relativenumber
set nu

" Format =========================================
set autoindent					
set smartindent
syntax enable						
syntax on							
set tabstop=4
" 将制表符扩展为空格
set expandtab						
" 设置格式化时制表符占用空格数
set softtabstop=4					
" 让vim把连续的空格视为一个制表符
set shiftwidth=4					
" 设置以unix格式保存文件
set fileformat=unix
" set foldmethod=indent             " 设置代码折叠方式为缩进

" Keymap =========================================
" 定义快捷键的前缀, 即<Leader>
let mapleader=" "
nmap <leader>s :source $HOME/_vimrc<cr>
nmap <leader>e :e $HOME/_vimrc<cr>
nmap <leader>ee :e E:\<cr>
nmap <leader>dd :e D:\<cr>


" 关闭提示音
set vb t_vb= 						
" 开启即时搜索
set is                              
set ignorecase
" 高亮显示搜索结果
set hlsearch
" vim 自身命令行模式智能补全
set wildmenu
" 右下角显示光标位置的状态行
set ruler							
" 避免必须保存修改才可以跳转buffer
set hidden 							
" 设置折叠层次 0表示全部折叠
set foldlevel=0                     

set mouse=a
set showmode
set showcmd
" 设置括号匹配
set showmatch                       
" 默认10进制
set nrformats=                      
" 显示状态栏
"set showtabline=2                   
" 禁止光标闪烁
set guicursor+=a:blinkon0           
