" ============================================================
" 	FileName:   _vimrc for Win10
" 	Date:       12.07.2016
" 	Email:      xilemon3@gmail.com
" 	Notes:      simple,simple,simple
" ============================================================

" Startup {{{
filetype plugin indent on							" 载入文件类型插件,和缩进
augroup ft_vim
    au!
    au FileType vim setlocal foldmethod=marker

augroup end
" }}}


" General {{{
set nocompatible                    " 设置不兼容vi模式
set nobackup						
set noswapfile
set history=1024                    " 命令行历史记录
set autoread                        " 自动更新文件
set clipboard+=unnamed              " vim默认寄存器与系统剪切版共享
" }}}

" Lang & Encoding {{{
set fileencoding=utf-8
set encoding=utf8									" 设置编码
set langmenu=zh_cn.utf-8							" 设置菜单栏编码
let $LANG="zh_CN.UTF-8"
language messages zh_CN.utf-8						" 解决consle输出乱码
set helplang=cn										" 设置帮助的语言为中文
" }}}

" Plugin {{{

filetype off
set rtp+=$VIM/vimfiles/bundle/Vundle.vim 			" Vundle的路径
call vundle#begin('$VIM/vimfiles/bundle/')			" 插件列表开始

" ----- Vundle ----- {{{
Plugin 'VundleVim/Vundle.vim'             
"  }}}

" ----- Theme ----- {{{
Plugin 'altercation/vim-colors-solarized'  			
"  }}}

" ----- airline ----- {{{
Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
set laststatus=2 					                " 始终显示状态栏
let g:airline_theme="papercolor"
"let g:airline_theme="solarized"
"let g:airline_theme="powerlineish"
"let g:airline_theme="base16"
let g:airline_powerline_fonts = 1
"  }}}

" ----- Emmet ----- {{{
Plugin 'mattn/emmet-vim'
"  }}}

" ----- MarkDown ----- {{{
Plugin 'plasticboy/vim-markdown'					
"  }}}

" ----- AutoPairs ----- {{{
Plugin 'jiangmiao/auto-pairs'						" 括号和引号自动补全
"  }}}

" ----- XML & HTML ----- {{{
Plugin 'othree/xml.vim'
"  }}}

filetype on
call vundle#end()
" }}}

" GUI {{{
set background=dark
colorscheme solarized
"colorscheme molokai
"colorscheme ph
source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
set cursorline						" 高亮显示当前行/列
set cursorcolumn
set number
set lines=40 columns=100 			" 设置gvim窗口大小
set guioptions-=T                   " 不显示工具栏/菜单栏
set guioptions-=m
set guioptions-=L
set guioptions-=r
set guioptions-=b
set guioptions-=e 					" 使用内置tab样式,而不是gui
set nolist
set guifont=DejaVuSansMonoForPowerLine_NF:h11:b:cANSI:qDRAFT
"set guifont=YaHei_Consolas_Hybrid:h11.5:b			" 设置 gvim 显示字体
" }}}

" Format {{{
set autoindent						" 自动缩进
set smartindent
syntax enable						" 开启语法高亮
syntax on							" 允许用指定语法高亮配色替换默认方案
set tabstop=4						
set expandtab						" 将制表符扩展为空格
set softtabstop=4					" 设置格式化时制表符占用空格数
set shiftwidth=4					" 让vim把连续的空格视为一个制表符
set foldmethod=indent
" }}}

" Other {{{
set mouse=a							" 启用鼠标
filetype on							" 侦测文件类型
set wildmenu						" vim 自身命令行模式智能补全 
set ruler							" 右下角显示光标位置的状态行
set vb t_vb= 						" 关闭提示音
set ignorecase                      " 搜索忽略大小写 
set hidden 							" 避免必须保存修改才可以跳转buffer
set showcmd							" 在状态栏显示正在输入的命令
set hls                             " 高亮显示搜索结果
set is                              " 输入即可搜索
"set spell                           " 拼写检查
"autocmd GUIEnter * simalt ~x		" 设定windows下 gvim 启动时最大化
" }}}
